sudo: required
services:
  - docker

before_install:
  - docker build -t zhdanovskiy/go-multi-fib-dev -f Dockerfile.dev .

script:
  - docker run zhdanovskiy/go-multi-fib-dev go test -v ./...

after_success:
  - docker build -t zhdanovskiy/go-multi-fib .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zhdanovskiy/go-multi-fib
