FROM golang

RUN go get github.com/go-redis/redis github.com/lib/pq

ADD . /go/src/github.com/ezhdanovskiy/docker-go-multi

RUN go install github.com/ezhdanovskiy/docker-go-multi

CMD ["/go/bin/docker-go-multi"]

EXPOSE 8080