version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/go/bin/docker-go-multi", "-component", "server"]
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/go/bin/docker-go-multi", "-component", "client"]
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/go/bin/docker-go-multi", "-component", "worker"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379