apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: zhdanovskiy/go-multi-fib
      ports:
        - containerPort: 8080
      command: ["./goapp"]
      args: ["-component", "client"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
